spring:
  kafka:
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092 # ${KAFKA_BOOTSTRAP:kafka:9092}
  mail:
    host: localhost # ${MAIL_HOST:mailhog}
    port: 1025 # ${MAIL_PORT:1025}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  kafka:
    topic: user-events

server:
  port: 8080

networks:
  default:
    name: micro-net
    external: true
